version: '2'

services:
    db:
        image: centos/mariadb
        volumes:
            - kiwi_db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: kiwi-1s-aw3s0m3
            MYSQL_DATABASE: kiwi
            MYSQL_USER: kiwi
            MYSQL_PASSWORD: kiwi

    web:
        depends_on:
            - db
        restart: always
        # NOTE: mrsenko/kiwi is a private image on Docker Store!
        image: mrsenko/kiwi:3.22
        ports:
            - 80
        volumes:
            - kiwi_uploads:/var/kiwi/uploads
        environment:
            KIWI_DB_HOST: db
            KIWI_DB_PORT: 3306
            KIWI_DB_NAME: kiwi
            KIWI_DB_USER: kiwi
            KIWI_DB_PASSWORD: kiwi

volumes:
    kiwi_db_data:
    kiwi_uploads:
